package unipaivakirja.test;
// Generated by ComTest BEGIN
import java.util.*;
import unipaivakirja.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END
import org.junit.jupiter.api.Test;

/**
 * Test class made by ComTest
 * @version 2021.07.26 14:42:32 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TagitTest {



  // Generated by ComTest BEGIN
  /** testAnnaTagit53 */
  @Test
  public void testAnnaTagit53() {    // Tagit: 53
    Tagit tagit = new Tagit(); 
    Tag tag1 = new Tag(1); tagit.lisaa(tag1); 
    Tag tag2 = new Tag(12); tagit.lisaa(tag2); 
    Tag tag3 = new Tag(1); tagit.lisaa(tag3); 
    Tag tag4 = new Tag(14); tagit.lisaa(tag4); 
    List<Tag> loytyneet; 
    loytyneet = tagit.annaTagit(2); 
    assertEquals("From: Tagit line: 64", 0, loytyneet.size()); 
    loytyneet = tagit.annaTagit(1); 
    assertEquals("From: Tagit line: 66", 2, loytyneet.size()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator82 */
  @Test
  public void testIterator82() {    // Tagit: 82
    Tagit tagit = new Tagit(); 
    Tag tag1 = new Tag(1); tagit.lisaa(tag1); 
    Tag tag2 = new Tag(2); tagit.lisaa(tag2); 
    Tag tag3 = new Tag(3); tagit.lisaa(tag3); 
    Tag tag4 = new Tag(4); tagit.lisaa(tag4); 
    Iterator<Tag> i2=tagit.iterator(); 
    assertEquals("From: Tagit line: 93", tag1, i2.next()); 
    assertEquals("From: Tagit line: 94", tag2, i2.next()); 
    assertEquals("From: Tagit line: 95", tag3, i2.next()); 
    assertEquals("From: Tagit line: 96", tag4, i2.next()); 
    try {
    assertEquals("From: Tagit line: 97", tag4, i2.next()); 
    fail("Tagit: 97 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}