package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.08.04 14:22:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TagienNimetTest {



  // Generated by ComTest BEGIN
  /** testPoista50 */
  @Test
  public void testPoista50() {    // TagienNimet: 50
    TagienNimet tagit = new TagienNimet(); 
    TagNimi t1 = new TagNimi(1,"tag"); 
    tagit.lisaa(t1); 
    assertEquals("From: TagienNimet line: 54", "1|tag", tagit.anna(0).toString()); 
    assertEquals("From: TagienNimet line: 55", 1, tagit.getLkm()); 
    tagit.poista(t1); 
    assertEquals("From: TagienNimet line: 57", 0, tagit.getLkm()); 
    assertEquals("From: TagienNimet line: 58", null, tagit.anna(0)); 
    TagNimi t2 = new TagNimi(1,"tag"); 
    TagNimi t3 = new TagNimi(2,"ta2"); 
    tagit.lisaa(t2); 
    tagit.lisaa(t3); 
    tagit.poista(t2); 
    TagNimi[] lista = tagit.getTagienNimet(); 
    for(int i = 0; i < lista.length; i++) { System.out.println(lista[i]); }
  } // Generated by ComTest END
}