package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.07.29 17:27:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TagTest {


  // Generated by ComTest BEGIN
  /** testParse96 */
  @Test
  public void testParse96() {    // Tag: 96
    Tag tag = new Tag(); 
    tag.parse("1,2"); 
    assertEquals("From: Tag line: 99", 2, tag.getTagID()); 
    assertEquals("From: Tag line: 100", 1, tag.getDreamID()); 
    assertEquals("From: Tag line: 102", "1,2", tag.toString()); 
  } // Generated by ComTest END
}