package unipaivakirja.test;
// Generated by ComTest BEGIN
import java.time.LocalDate;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.08.04 13:53:08 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UnetTest {



  // Generated by ComTest BEGIN
  /** testLisaa70 */
  @Test
  public void testLisaa70() {    // Unet: 70
    Unet unet = new Unet(); 
    assertEquals("From: Unet line: 72", 0, unet.getLkm()); 
    Uni u1 = new Uni(); 
    Uni u2 = new Uni(); 
    Uni u3 = new Uni(); 
    unet.lisaa(u1); 
    unet.lisaa(u2); 
    unet.lisaa(u3); 
    assertEquals("From: Unet line: 81", 3, unet.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaPaivamaarat222 */
  @Test
  public void testAnnaPaivamaarat222() {    // Unet: 222
    Unet unet = new Unet(); 
    Uni u1 = new Uni(); u1.setPaivamaara("2021-08-01"); 
    Uni u2 = new Uni(); u2.setPaivamaara("2021-08-03"); 
    Uni u3 = new Uni(); u3.setPaivamaara("2021-08-02"); 
    unet.lisaa(u1); 
    unet.lisaa(u2); 
    unet.lisaa(u3); 
    for (LocalDate ld : unet.annaPaivamaarat() ) {
    System.out.println(ld.toString()); 
    }
    ArrayList<LocalDate> pvmt = unet.annaPaivamaarat(); 
    assertEquals("From: Unet line: 237", "2021-08-03", pvmt.get(2).toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaAikajakso256 */
  @Test
  public void testAnnaAikajakso256() {    // Unet: 256
    Uni u1 = new Uni(); u1.setPaivamaara("2021-08-01"); u1.setKesto(8); 
    Uni u2 = new Uni(); u2.setPaivamaara("2021-08-03"); u2.setKesto(7); 
    Uni u3 = new Uni(); u3.setPaivamaara("2021-08-02"); u3.setKesto(5); 
    Unet unet = new Unet(); 
    unet.lisaa(u1); 
    unet.lisaa(u2); 
    unet.lisaa(u3); 
    assertEquals("From: Unet line: 266", 2, unet.annaAikajakso(2).size()); 
    assertEquals("From: Unet line: 267", "2021-08-03", unet.annaAikajakso(2).get(0).toString()); 
  } // Generated by ComTest END
}