package unipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import unipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2021.08.05 10:07:37 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class UniTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi79 */
  @Test
  public void testRekisteroi79() {    // Uni: 79
    Uni u1 = new Uni(); 
    assertEquals("From: Uni line: 81", 0, u1.getDreamID()); 
    u1.rekisteroi(); 
    Uni u2 = new Uni(); 
    u2.rekisteroi(); 
    int n1 = u1.getDreamID(); 
    int n2 = u2.getDreamID(); 
    n1 = n2-1; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse215 */
  @Test
  public void testParse215() {    // Uni: 215
    Uni uni = new Uni(); 
    uni.parse("1|/polku|8|01.01.2021|5"); 
    assertEquals("From: Uni line: 218", 5, uni.getArvio()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString263 */
  @Test
  public void testToString263() {    // Uni: 263
    Uni u = new Uni(); 
    Uni u2 = new Uni(); 
    u.parse("   1|uni1.txt|8|13.1.22|2"); 
    assertEquals("From: Uni line: 267", true, u.toString().startsWith("1|uni1.txt")); 
  } // Generated by ComTest END
}